name: flutter_firebase
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.2
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter

  flutter_core:
    git:
      url: https://github.com/bemohansingh/flutter_core.git
      ref: main
  flutter_facebook_auth: ^4.3.0
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
